apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: us.gcr.io/meta-internal/gddo-frontend:latest
        env:
          - name: HOST
            value: :8080
          - name: TLS_HOST
            value: :8081
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        volumeMounts:
        - name: ssl
          mountPath: /ssl
      volumes:
        - name: ssl
          secret:
            secretName: gddo-ssl
