apiVersion: v1
kind: Service
metadata:
  name: gddo
  labels:
    name: gddo
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    name: gddo
